baseURL = 'https://blog.sayeedhoda.com/'
languageCode = 'en-us'
title = 'Blog Sayeed'

[[params.socialIcons]]
name = "github"
url = "https://github.com/Mohd-Sayeedul-Hoda"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/HodaSayeed"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/mohd-sayeedul-hoda/"

[[params.socialIcons]]
name = "-"
url = "https://www.linkedin.com/in/mohd-sayeedul-hoda/"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"
